name = "cloudflare_temp_email"
main = "src/worker.ts"
compatibility_date = "2023-12-01"
node_compat = true
# if you want use custom_domain, you need to add routes
# routes = [
# 	{ pattern = "temp-email-api.bysshe.co.uk", custom_domain = true },
# ]

# enable cron if you want set auto clean up
# [triggers]
# crons = [ "0 0 * * *" ]

# send_email = [
#    { name = "SEND_MAIL" },
# ]

[vars]
# TITLE = "Custom Title" # custom title
# ANNOUNCEMENT = "Custom Announcement"
PREFIX = "tmp"
# address check REGEX, if not set, will not check
# ADDRESS_CHECK_REGEX = "^(?!.*admin).*"
# address name replace REGEX, if not set, the default is [^a-z0-9]
 ADDRESS_REGEX = "[^a-z0-9]"
# (min, max) length of the adderss, if not set, the default is (1, 30)
 MIN_ADDRESS_LEN = 1
 MAX_ADDRESS_LEN = 30
# IF YOU WANT TO MAKE YOUR SITE PRIVATE, UNCOMMENT THE FOLLOWING LINES
 PASSWORDS = ["4dfaed4430", "3ld3rflow3r"]
# For admin panel
 ADMIN_PASSWORDS = ["4Dfaed4430"]
# warning: no password or user check for admin portal
 DISABLE_ADMIN_PASSWORD_CHECK = false
# ADMIN CONTACT, CAN BE ANY STRING
 ADMIN_CONTACT = "josh@bysshe.co.uk"
DEFAULT_DOMAINS = ["bysshe.co.uk" , "learnwithjules.com"] # domain name for no role users
DOMAINS = ["bysshe.co.uk" , "learnwithjules.com"] # all domain names
 USER_DEFAULT_ROLE = "vip" # default role for new users(only when enable mail verification)
 ADMIN_USER_ROLE = "admin" # the role which can access admin panel
# User roles configuration, if domains is empty will use default_domains, if prefix is null will use default prefix, if prefix is empty string will not use prefix
 USER_ROLES = [
    { domains = ["bysshe.co.uk" , "learnwithjules.com"], role = "vip", prefix = "vip" },
    { domains = ["bysshe.co.uk"], role = "admin", prefix = "josh" },
 ]
JWT_SECRET = "xxx"
BLACK_LIST = ""
# Allow users to create email addresses
ENABLE_USER_CREATE_EMAIL = true
# Allow users to delete messages
ENABLE_USER_DELETE_EMAIL = true
# Allow automatic replies to emails
ENABLE_AUTO_REPLY = false
# Allow webhook
 ENABLE_WEBHOOK = true
# Footer text
# COPYRIGHT = "Dream Hunter"
 DISABLE_SHOW_GITHUB = true
# default send balance, if not set, it will be 0
 DEFAULT_SEND_BALANCE = 1
 NO_LIMIT_SEND_ROLE = "vip" # the role which can send emails without limit
# Turnstile verification
 CF_TURNSTILE_SITE_KEY = "0x4AAAAAAAiQ8nbN5Up3VO32"
 CF_TURNSTILE_SECRET_KEY = "0x4AAAAAAAiQ8l6XKMc8lKaXIlOuuIDObW8"
# telegram bot
# TG_MAX_ADDRESS = 5
# global forward address list, if set, all emails will be forwarded to these addresses
# FORWARD_ADDRESS_LIST = ["xxx@xxx.com"]

[[d1_databases]]
binding = "DB"
database_name = "email-api"
database_id = "2ce8db06-ba70-4c1f-8aaa-eda21361b254"

# kv config for send email verification code
 [[kv_namespaces]]
 binding = "KV"
 id = "71998220c57b4e1ea3e57194891d7b7b"

# ratelimit config for /api/new_address
 [[unsafe.bindings]]
 name = "RATE_LIMITER"
 type = "ratelimit"
 namespace_id = "1001"
# # 10 requests per minute
 simple = { limit = 10, period = 60 }
